<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>RoslynMeow.Math.Number</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <AssemblyName>RoslynMeow.Math.Number</AssemblyName>
    <AssemblyTitle>Numbers</AssemblyTitle>
    <NuGetAuditMode>all</NuGetAuditMode>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>RoslynMeow.Math.Number</PackageId>
    <Title>RoslynMeow.Math.Number</Title>
    <Version>1.0.0</Version>
    <Authors>DavidSciMeow</Authors>
    <Company>Electronicute</Company>
    <Product>RoslynMeow.Math.Number</Product>
    <Description>its a bignumber lib
 with grandint and bigfraction</Description>
    <Copyright>@2025 Electronicute</Copyright>
    <PackageProjectUrl>https://github.com/RoslynMeow/Math</PackageProjectUrl>
    <PackageReadmeFile>ReadMe.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/RoslynMeow/Math</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>math, grandint, fraction, number</PackageTags>
    <PackAsTool>False</PackAsTool>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\ReadMe.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>